project:
  type: website

website:
  title: "Book website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - lazega.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
editor: visual

